version: '3.8'

services:
  backend-django:
    build:
      context: ./backend-django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend-django/.env
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DJANGO_API_URL=http://localhost:8000/api
      - NEXT_PUBLIC_TORRENT_URL=http://localhost:3005
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - backend-django
      - torrent
    restart: unless-stopped

  torrent:
    build:
      context: ./torrent
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - ./torrent:/app
      - /app/node_modules
    restart: unless-stopped
