# Generated by Django 6.1.1 on 2026-10-01 08:27

import django.utils.timezone
import movies.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=36)),
                ('studio_id', models.CharField(max_length=36)),
                ('allowed_countries', movies.models.SafeJSONField(default=list)),
                ('royalty_rate_per_hour', models.FloatField(default=0.15)),
                ('status', models.CharField(default='active', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', movies.models.SafeJSONField(default=list)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('rating', models.CharField(default='PG-13', max_length=10)),
                ('imdb_score', models.FloatField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', movies.models.SafeJSONField(default=list)),
                ('tags', movies.models.SafeJSONField(default=list)),
                ('stream_type', models.CharField(default='full', max_length=20)),
                ('trailer_youtube_id', models.CharField(blank=True, max_length=50, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('video_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('hls_manifest_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('studio_id', models.CharField(blank=True, max_length=36, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('movie_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('genres', movies.models.SafeJSONField(default=list)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', movies.models.SafeJSONField(default=list)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('progress_seconds', models.IntegerField(default=0)),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
                'managed': True,
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
